name: Tests and linters

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  ruff:
    name: Ruff
    permissions:
      contents: read

    steps:
      - name: Clone
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Run ruff
        uses: astral-sh/ruff-action@84f83ecf9e1e15d26b7984c7ec9cf73d39ffc946 # v3
