name: Tests and linters

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  ruff:
    name: Ruff
    permissions:
      contents: read

    steps:
      - name: Clone
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Run ruff
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
